@ApiDemo_HostAddress = https://localhost:7222

### Test SignUp endpoint
POST {{ApiDemo_HostAddress}}/api/Auth/SignUp
Accept: text/plain
Content-Type: application/json

{
  "username": "mohammed85",
  "email": "mohammed@hotmail.com",
  "password": "987654321"
}

### Test Login endpoint

POST {{ApiDemo_HostAddress}}/api/Auth/Login
Accept: text/plain
Content-Type: application/json

{ 
  "usingUsername": true,
  "username": "mohammed85",
  "email": "mohammed@hotmail.com",
  "password": "987654321"
}