@ApiDemo_HostAddress = https://localhost:7222

### Test SignUp endpoint
POST {{ApiDemo_HostAddress}}/api/Users/Auth/SignUp
Accept: text/plain
Content-Type: application/json

{
  "username": "asdasd",
  "email": "mohammed@hot.com",
  "password": "1asd45f15asd1f51asd6f1"
}

###