@ApiDemo_HostAddress = https://localhost:7222

### Upload avatar image
PUT {{ApiDemo_HostAddress}}/api/users/Avatar/{{Uuid}}
Content-Type: multipart/form-data; boundary=----BOUNDARY
Authorization: {{AccessToken}}

------BOUNDARY
Content-Disposition: form-data; name="file"; filename="file.png"
Content-Type: image/png

< ./avatar.png
------BOUNDARY--

### Get avatar image
GET {{ApiDemo_HostAddress}}/api/users/avatar/{{Uuid}}
Content-Type: image/png

