@ApiDemo_HostAddress = https://localhost:7222
@Username = mohammed85
@Email = mohammed@hotmail.com
@Password = 987654321

### Test SignUp endpoint
# @name signup
POST {{ApiDemo_HostAddress}}/api/Account/SignUp
Accept: application/json
Content-Type: application/json

{
  "username": "{{Username}}",
  "email": "{{Email}}",
  "password": "{{Password}}"
}

> {%
    // Extract fields from the JSON response into global variables
    client.global.set("Uuid", response.body.tokensData.ownerUUID);
    client.global.set("AccessToken", response.body.tokensData.accessToken);
%}

### Test PasswordReset
PUT {{ApiDemo_HostAddress}}/api/Account/ChangePassword
Accept: application/json
Content-Type: application/json
Authorization: {{AccessToken}}

{
  "uuid": "{{Uuid}}",
  "oldPassword": "{{Password}}",
  "newPassword": "{{Password}}"
}
